package dev.omega.arcane.compiler;

/**
 * Simple functional interface implemented by generated bytecode evaluators.
 */
@FunctionalInterface
public interface CompiledEvaluator {
    float evaluate();
}
