package dev.omega.arcane.codegen;

/**
 * Simple functional interface implemented by generated bytecode evaluators.
 */
@FunctionalInterface
public interface CompiledEvaluator {

    float evaluate();
}
